# Generated by Django 5.0.3 on 2024-10-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kittens_api', '0002_alter_kitten_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='score',
        ),
    ]
