# Generated by Django 5.0.3 on 2024-10-06 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittens_api', '0005_alter_kitten_owner_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitten',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kittens_api.user'),
        ),
    ]
